Currency conversion v beta
latajacysmok/Road_to_Csharp_developer pull request #21
Opened 2023-04-03 10:26 UTC by latajacysmok

big change.

2023-04-03 12:05 UTC, whyyy requested changes

2023-04-03 12:05 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Currency/Currency.csproj
>  <Project Sdk="Microsoft.NET.Sdk">
`Currency` projekt nie jest dodany do solucji.
Folder `Currency` jest dodany do repo, ale brakuje go w solucji.
Czy jest w ogole potrzebny?

2023-04-03 12:05 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/CurrencyConversion/Program.cs
>              }
Appka z perpektywy użytkownika, moglaby byc jeszcze bardziej intuicyjna.
Przykladowo, jesli chcemy sprzedac  i wprowadzic wlasny kurs, to musimy:
1. Wybrac `No` czyli wpisac `2` - dla buy
2. Wybrac `Yes` czyli wpisac `1` - dla sell
3. Wybrac `Yes` czyli wpisac `1` - dla wprowadzenia wlasnego kursu
Zostawiam do przemyslenia.

Druga rzecz to zly komunikat w sytuacji:
![image](https://user-images.githubusercontent.com/11249681/229488763-0c75f010-954c-418e-b1a0-2bb22a0ef38d.png)

2023-04-03 12:05 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/CurrencyConversion/Program.cs
>              }
Daloby rade wypisac kursy dla wybranej waluty, zanim uzytkownik zdecyduje, czy sam wprowadza kurs?

2023-04-03 12:05 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Decide/CurrencyName.cs
> +        public enum CurrencyDefault
Zagniezdziles enuma wewnatrz deklaracji klasy. 
Lepiej, zeby ten enum byl w osobnym pliku, tez z rozszerzeniem `.cs` ale w srodku zamiast klasy bedzie enum.
Dzieki temu, nie bedziesz musial sie odwolywac do `klasa.enum`, bo teraz masz odwolania `Names.CurrencyDefault`

2023-04-03 12:05 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Decide/CurrencyName.cs
> +    public class Names
Nazwa klasy tu to `Names` a pliku to `CurrencyName`, do uporzadkowania

2023-04-03 12:05 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Decide/CurrencyName.cs
> +                else Console.WriteLine("Currency name is required, please try again.");
`else` niepotrzebny, jesli to wypisanie sie wywola, to juz bedziemy poza ifem/elsem.

2023-04-03 12:05 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Decide/CurrencyName.cs
> +        public string CurrencyUser(bool ifBuy)
Nazwa, where czasownik

2023-04-03 12:05 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Decide/MakingDecision.cs
> +    /*public class Instruction
Zakomentowany kod

2023-04-03 12:05 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Option/Cantor.cs
> +        Option option = new Option();
Obiekt tworzony tu, po to by wywolac metode.
Poziom wyzej w `Transaction` tez tworzysz obiekt `Option`.
Zmienilbym metode `GetCurrency` na metode z parameterem, ktory bedziesz przekazywal w klasie `Transaction`.

2023-04-03 12:05 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Option/Cantor.cs
> +        Names name = new Names();
Mysle, ze lepiej, zeby ten obiekt byl tworzony wyzej w `Transaction`
W ogole do zastanowienia sie: 
1. czy potrzebujemy tej klasy `Names`
2. czy to jest ok, ze dopiero wewnatrz `Cantor` wolamy metode do wyciagania nazwy waluty.

2023-04-03 12:05 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Option/Cantor.cs
> +        public Names.CurrencyDefault GetCurrency()
Te metody w stylu `Get` dzialaja ok, ale, co jesli obiekt typu `Currency` bedziemy tworzyc poziom wyzej w `Transaction`, powinno to duzo uproscic :)

2023-04-03 12:05 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Option/Option.cs
> +    public class Option
Nadal nazwy niektorych metod nie maja czasownikow

2023-04-03 12:05 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Option/Transaction.cs
> +    public class Transaction
Z praktycznego podejscia, transakcja kojarzy sie z jakas operacja pieniezna, wiec nazwa klasy ekstra.
Patrzac na to, ze chcemy wymienic walute, to przydaloby sie zeby transakcja wiedziala o pewnych rzeczach:
1.  O walucie - czyli twoje `Currency`
2.  O wartosciach wprowadzonych przez uzytkownika - twoje `Option`

Takze mysle ze rozsadne podejscie to tworzenie obiektu `Currency` w `Transaction`.
No i `Option` zeby wywolywac metody potrzebne do otrzymania wartosci wprowadzanych przez usera.

To co sie znajduje w `CurrencyName` klasie chyba przenioslbym do `Option` po prostu.

Co do klasy `Cantor`, nie wiem czy bedzie potrzeba po akcjach, ktore wypisalem wyzej :)

2023-04-03 12:05 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Decide/Currency.cs
> +            Name         = name;
Wyglada ciekawie z tymi spacjami ;D 
ale raczej tak sie nie robi ;p

2023-04-03 17:56 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Currency/Currency.csproj
>  <Project Sdk="Microsoft.NET.Sdk">
No ciekawe, jak się mógł zagubić :D

2023-04-03 18:01 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Decide/CurrencyName.cs
> +    public class Names
Ty faktycznie xD

2023-04-03 18:28 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Decide/CurrencyName.cs
> +                else Console.WriteLine("Currency name is required, please try again.");
hmmm, musisz mi wytłumaczyć bo nie czaję.

2023-04-04 08:24 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Decide/CurrencyName.cs
> +                else Console.WriteLine("Currency name is required, please try again.");
skasuj else i zostaw CW

2023-04-04 08:33 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Option/Cantor.cs
> +        public Names.CurrencyDefault GetCurrency()
wywoływać metody currency w translation

2023-04-04 08:35 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Option/Transaction.cs
> +    public class Transaction
Za dużo obiektów mozna stworzyć raz i wszystkie metody moga sobie z niego korzystać i wyciągac co mu trezba.

2023-04-05 04:15 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Decide/CurrencyName.cs
> +        public enum CurrencyDefault
done.

2023-04-05 04:21 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Option/Option.cs
> +    public class Option
Coś tam poprawiłem ale wiadomo i tak pewnie nie wszytsko 🔢

2023-04-05 04:26 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Decide/CurrencyName.cs
> +        public string CurrencyUser(bool ifBuy)
ehhh..., a tak: UserEntersNameOfCurrency

2023-04-05 04:26 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Decide/MakingDecision.cs
> +    /*public class Instruction
done.

2023-04-05 10:42 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/CurrencyConversion/Program.cs
>              }
Zrobiłem trochę inaczej wypisałem wszystkie dostępne waluty i ich wartość gdyż ponieważ dla konkretnej waluty mamy w momencie gdy wybierzemy już że korzystamy z wartości domyślnych a ponad to walute wybieram po decyzji czy sam czy nie sam i musiało by się dużo zmienić.

2023-04-06 10:13 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Decide/CurrencyName.cs
> +                else Console.WriteLine("Currency name is required, please try again.");
done.

2023-04-06 10:15 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Option/Cantor.cs
> +        Option option = new Option();
done.

2023-04-06 10:16 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Option/Cantor.cs
> +        Names name = new Names();
ni ma już tej klasy xD

2023-04-07 05:01 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/CurrencyConversion_vBeta/Decide/Currency.cs
> +            Name         = name;
jeszcze zostawie xD

2023-04-07 08:55 UTC, merged