Bmi
latajacysmok/Road_to_Csharp_developer pull request #22
Opened 2023-04-07 07:02 UTC by latajacysmok

Change approach to solution.

2023-04-13 06:38 UTC, whyyy requested changes

2023-04-13 06:38 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/BMI/Interface.csproj
> +    <ProjectReference Include="..\ClassLibrary1\BMI.csproj" />
Rozjechaly sie nazwy projektow
![image](https://user-images.githubusercontent.com/11249681/230565142-7c470942-37f8-4c02-adb7-81dcbd155f6d.png)

![image](https://user-images.githubusercontent.com/11249681/230565351-e4f11cf7-0b2f-41e0-94f1-eff58847248e.png)

2023-04-13 06:38 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/ClassLibrary1/BmiCalculator.cs
> +        {
Moznaby popracowac jeszcze z property i napisac wlasne, zamiast tych automatycznie generowanych ;p 
Cos w stylu jak robiles w kantorze.

2023-04-13 06:38 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/ClassLibrary1/BmiCalculator.cs
> +            double missingDiffToRightBmi = 18.5 - BmiCalculation;
wartosc `18.5` moglaby byc wyciagnieta jako prywatna stała, bo uzywasz jej tu i w innej metodzie

2023-04-13 06:38 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/ClassLibrary1/BmiCalculator.cs
> +            double missingDiffToRightBmi = BmiCalculation - 24.9;
wartosc `24.9` moglaby byc wyciagnieta jako prywatna stała, bo uzywasz jej tu i w innej metodzie

2023-04-13 06:38 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/ClassLibrary1/BmiCalculator.cs
> +        public double CalculateHowMuchShouldBeGained { get; }
uzyte tylko w tej klasie

2023-04-13 06:38 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/ClassLibrary1/BmiCalculator.cs
> +        public double CalculateHowMuchShouldBeLost { get; }
uzyte tylko w tej klasie

2023-04-13 06:38 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/Data/ValueStorage.cs
> +                name = Console.ReadLine();
Wyglada na niepotrzebne, ze masz pole prywatne i property `Name`. Od razu ustawialbym property tutaj.
Mysle, ze ta metoda `GetName` powinna byc w klasie `Performer` a tu tylko wolanie `instancja.NazwaMetody`

2023-04-13 06:38 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/Option/Performer.cs
> +                if (decisionToExitTheProgram == (int)MakingDecision.Yes)
visual studio cos podpowiada tutaj

2023-04-13 06:38 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/Option/Performer.cs
> +                else if (decisionToExitTheProgram == (int)MakingDecision.No) LeaveProgramme();
visual studio cos podpowiada tutaj

2023-04-16 06:53 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/BMI/Interface.csproj
> +    <ProjectReference Include="..\ClassLibrary1\BMI.csproj" />
done.

2023-04-16 06:57 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/ClassLibrary1/BmiCalculator.cs
> +            double missingDiffToRightBmi = 18.5 - BmiCalculation;
done,

2023-04-16 06:58 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/ClassLibrary1/BmiCalculator.cs
> +            double missingDiffToRightBmi = BmiCalculation - 24.9;
nawet dałem const żeby była stała ;)

2023-04-16 06:58 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/ClassLibrary1/BmiCalculator.cs
> +        public double CalculateHowMuchShouldBeGained { get; }
done.

2023-04-16 06:59 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/ClassLibrary1/BmiCalculator.cs
> +        public double CalculateHowMuchShouldBeLost { get; }
done.

2023-04-16 09:58 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/Data/ValueStorage.cs
> +                name = Console.ReadLine();
Chyba zrobiłem.

2023-04-16 10:00 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/Option/Performer.cs
> +                if (decisionToExitTheProgram == (int)MakingDecision.Yes)
moje VS mi nic nie podpowiada xD.

2023-04-16 10:01 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/Option/Performer.cs
> +                else if (decisionToExitTheProgram == (int)MakingDecision.No) LeaveProgramme();
tutej też nie xD

2023-04-16 14:53 UTC, whyyy commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/BMI/Interface.csproj
> +    <ProjectReference Include="..\ClassLibrary1\BMI.csproj" />
teraz jest solucja `BMI_VBeta` + projekty `BMI` i `BMI_vBeta` 
istnieje tez nadal folder `ClassLibrary`, ktory jest pusty

2023-04-18 06:27 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/BMI/Interface.csproj
> +    <ProjectReference Include="..\ClassLibrary1\BMI.csproj" />
Done

2023-04-20 19:10 UTC, latajacysmok commented on Learning_test_automation/Spotkanie6_Zadania/BMI_vBeta/ClassLibrary1/BmiCalculator.cs
> +        {
done.

2023-05-12 08:12 UTC, merged