New program: School Diary
latajacysmok/Road_to_Csharp_developer pull request #25
Opened 2023-05-22 09:42 UTC by latajacysmok

A proving ground against the object-oriented approach and everything we learn.

2023-05-22 15:17 UTC, whyyy requested changes
Generalnie niezle :p 
widac efekty nauki, ale trzeba dalej konsekwentnie dbac o szczegoly

2023-05-22 15:17 UTC, whyyy commented on Learning_test_automation/Projekt#1/TeachersGradebook/SchoolData/Student.cs
> +        private int Grade { get; set; }
Nazwa `Grade` bardziej kojarzy sie z oceną, jaka moze uzystkac uczen.
Chyba tu miales na mysli klase, do ktorej uczeszcza - jako poziom nauki.
Uzylbym nazwy `EducationYear` zeby byc bardziej spojnym z ang xD 
https://www.brightworldguardianships.com/en/guardianship/british-education-system/

2023-05-22 15:17 UTC, whyyy commented on Learning_test_automation/Projekt#1/TeachersGradebook/SchoolData/Student.cs
> +        private static int idCounter = 0;
troche śliskie rozwiazanie, na ten moment zadziala :p

2023-05-22 15:17 UTC, whyyy commented on Learning_test_automation/Projekt#1/TeachersGradebook/SchoolData/SubjectDegree.cs
> +        public double[] ratings = { 1, 1.5D, 2, 2.5D, 3, 3.5D, 4, 4.5D, 5, 5.5D, 6 };
Pole uzyte tylko w 1 klasie, wydaje mi sie niepotrzebne jako osobna klasa, przynajmniej nie w takiej formie

2023-05-22 15:17 UTC, whyyy commented on Learning_test_automation/Projekt#1/TeachersGradebook/SchoolData/SchoolData.csproj
> +</Project>
W wartswie danych, czyli w projekcie `SchoolData` wg mnie brakuje reprezentacji dla obiektu oceny - uwazam ze typ double jest zbyt prosty, to znaczy, wiemy tylko o wartosci oceny, ale nie wiemy:
* czyja jest to ocena
* za co jest to ocena
* jaki przedmiot
* (bonus: jaka wage ma ocena - masz klase, ktora moglaby liczyc wage oceny, ale nie uzywasz jej)

2023-05-22 15:17 UTC, whyyy commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/Degree.cs
> +    public class Degree
Lepsza nazwa to `Grade` albo `Mark`, bo `Degree` kojarzy sie bardziej ze stopniem naukowym, albo skala temperatury

2023-05-22 15:17 UTC, whyyy commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/TeachersRoom.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Nazwa projektu `TeachersRoom` niewiele mowi ;p 
lepsza nazwa to np `Infrastructure`

2023-05-22 15:17 UTC, whyyy commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/Menu.cs
> +        SchoolGradeWizard schoolGradeWizard = new SchoolGradeWizard();
Czy `Menu` powinno byc odpowiedzialne za tworzenie tych kolekcji?

2023-05-22 15:17 UTC, whyyy commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/Menu.cs
> +        public void ListingPossibilities()
Nazwa do poprawki

2023-05-22 15:17 UTC, whyyy commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/Option.cs
> +    public class Option
Troche dobrze troche zle z nazwami metod w tej klasie, do poprawek

2023-05-22 15:17 UTC, whyyy commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/SchoolGradeWizard.cs
> +        SchoolSubjects schoolSubjects = new SchoolSubjects();
Enum, w dodatku uzywany lokalnie tylko

2023-05-22 15:17 UTC, whyyy commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/SchoolGradeWizard.cs
> +    public class SchoolGradeWizard
Nie jestem do konca przekonany, zeby metody ktore pobieraja dane od uzytkownika byly tutaj implementowane :p 
Lepiej trzymac to osobno w klasie `Option`

2023-05-22 15:17 UTC, whyyy commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/SchoolGradeWizard.cs
> +    public class SchoolGradeWizard
Tak samo metody, ktore wypisuja jakies dane, powinny byc w `Menu` wg mnie

2023-05-22 15:17 UTC, whyyy commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/SchoolGradeWizard.cs
> +        private void PrintouSchoolGradesPerSubject(List<double> subject)
Poetycka nazwa :D ale do poprawy

2023-05-22 15:17 UTC, whyyy commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/TeachersDiary.cs
> +        public void AddingGrades(List<double> schoolSubjects)
Nazwa do poprawy
Metoda robi wiecej niz nazwa o tym mowi ;p

2023-05-22 15:17 UTC, whyyy commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/TeachersDiary.cs
> +        private int Id { get; set; }
`Id` jest, ale co z nim dalej?

2023-05-22 15:17 UTC, whyyy commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/StudentCreator.cs
> +        public StudentCreator()
Troche inne podejscie bym zastosowal, pogadamy na spotkaniu

2023-05-22 18:35 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/SchoolData/Student.cs
> +        private int Grade { get; set; }
bez komentarza... xD

2023-05-22 18:35 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/SchoolData/Student.cs
> +        private static int idCounter = 0;
ale co? Czemu śliskie? Mamy id dla każdego ucznia :D

2023-05-22 18:43 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/SchoolData/SubjectDegree.cs
> +        public double[] ratings = { 1, 1.5D, 2, 2.5D, 3, 3.5D, 4, 4.5D, 5, 5.5D, 6 };
Człowiek chce podejść do tematu obiektowo bo może te oceny jeszcze się gdzieś przydadzą ale nie już trzeba w zarodku zadusić xD

2023-05-22 18:45 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/Degree.cs
> +    public class Degree
te nazwy...

2023-05-22 18:45 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/TeachersRoom.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
+

2023-05-22 18:50 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/Menu.cs
> +        public void ListingPossibilities()
wymyśliłem cos co na 100% Ci sie spodoba 🗡️

2023-05-22 18:55 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/Option.cs
> +    public class Option
łooo Panie teraz wyskoczysz z kapci, zobaczysz.

2023-05-22 18:55 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/SchoolGradeWizard.cs
> +        SchoolSubjects schoolSubjects = new SchoolSubjects();
ok ok

2023-05-22 18:59 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/SchoolGradeWizard.cs
> +        private void PrintouSchoolGradesPerSubject(List<double> subject)
[*]

2023-05-22 19:03 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/TeachersDiary.cs
> +        public void AddingGrades(List<double> schoolSubjects)
Poprawiłem ale nie wiem czy dobrze zrozumiałem.

2023-05-22 19:11 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/TeachersDiary.cs
> +        private int Id { get; set; }
Nooo... każdy uczeń ma tak jakby swój dziennik czyli każdy uczeń ma przypisany do siebie dziennik z ocenami. I rozpoznajemy go po tym id. Źle?

2023-05-23 08:11 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/SchoolData/Student.cs
> +        private static int idCounter = 0;
co jeśli zaimportujemy uczniów. Należy przeszukać listę i nadać największy numer plus 1.

2023-05-23 08:22 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/Option.cs
> +    public class Option
zmienić nazwę pierwszej metody: 5 linia.

2023-05-23 08:25 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/SchoolGradeWizard.cs
> +    public class SchoolGradeWizard
Ograniczyć Klasy żeby nie robiły za wiele i raczej w jednej tematyce.

2023-05-23 08:26 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/SchoolGradeWizard.cs
> +    public class SchoolGradeWizard
Podział odpowiedzialności, każda klasa jest specjalistą w wąskim zakresie.

2023-05-23 08:28 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/TeachersDiary.cs
> +        public void AddingGrades(List<double> schoolSubjects)
Rozdziel tą metodę na dwie mniejsze.

2023-05-23 08:30 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/TeachersDiary.cs
> +        public void AddingGrades(List<double> schoolSubjects)
Jedna odpowiedzialna za dodawnie a druga za wypisywanie.

2023-05-23 08:35 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/TeachersDiary.cs
> +        private int Id { get; set; }
To Id jest nie potrzebne. Po prostu.

2023-05-23 18:44 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/Option.cs
> +    public class Option
Teraz powinno być git.

2023-05-23 18:48 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/TeachersDiary.cs
> +        public void AddingGrades(List<double> schoolSubjects)
sie robi!!!

2023-05-23 19:52 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/TeachersDiary.cs
> +        private int Id { get; set; }
done.

2023-05-29 11:38 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/SchoolData/Student.cs
> +        private static int idCounter = 0;
done.

2023-05-29 11:39 UTC, latajacysmok commented on Learning_test_automation/Projekt#1/TeachersGradebook/TeachersRoom/Menu.cs
> +        SchoolGradeWizard schoolGradeWizard = new SchoolGradeWizard();
pewnie nie 🍡

2023-05-31 07:48 UTC, merged